/*
 * This file is part of BBCT.
 *
 * Copyright 2012 codeguru <codeguru@users.sourceforge.net>
 *
 * BBCT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * BBCT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package bbct.gui;

import bbct.data.BaseballCardIO;
import bbct.exceptions.IOException;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * TODO: JavaDoc
 * 
 * @author codeguru <codeguru@users.sourceforge.net>
 */
public class BBCTFrame extends javax.swing.JFrame {

    /**
     * Name used for {@link MainPanel} card.
     */
    public static final String MENU_CARD_NAME = "menu";
    /**
     * Name used for {@link AddCardsPanel} card.
     */
    public static final String ADD_CARDS_CARD_NAME = "addCards";
    /**
     * Name used for {@link FindCardsMenuPanel} card.
     */
    public static final String FIND_CARDS_MENU_CARD_NAME = "findCardsMenu";
    /**
     * Name used for {@link EditCardPanel} card.
     */
    public static final String EDIT_CARDS_PANEL_NAME = "editCards";
    /**
     * Name used for {@link FindCardsByYearPanel} card.
     */
    public static final String FIND_CARDS_BY_YEAR_CARD_NAME = "findCardsByYear";
    /**
     * Name used for {@link FindCardsByNumberPanel} card.
     */
    public static final String FIND_CARDS_BY_NUMBER_CARD_NAME = "findCardsByNumber";
    /**
     * Name used for {@link FindCardsByYearAndNumberPanel} card.
     */
    public static final String FIND_CARDS_BY_YEAR_AND_NUMBER_CARD_NAME = "findCardsByYearAndNumber";
    /**
     * Name used for {@link FindCardsByPlayerNamePanel} card.
     */
    public static final String FIND_CARDS_BY_PLAYER_NAME_CARD_NAME = "findCardsByPlayerName";
    /**
     * Name used for {@link AboutPanel} card.
     */
    public static final String ABOUT_CARD_NAME = "about";

    /**
     * Creates {@link BBCTFrame}.
     */
    public BBCTFrame() {
        this.initComponents();
        this.centerFrame();
    }

    /**
     * Creates {@link BBCTFrame}.
     *
     * @param bcio
     */
    public BBCTFrame(BaseballCardIO bcio) {
        this.bcio = bcio;
        this.initComponents();
        this.centerFrame();
    }

    /**
     * Set instructions for the user shown at the top of the window.
     *
     * @param instructions
     */
    public void setInstructions(String instructions) {
        this.instructionLabel.setText(instructions);
    }

    private void centerFrame() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new MainPanel(this.bcio);
        javax.swing.JPanel instructionPanel = new javax.swing.JPanel();
        instructionLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baseball Card Tracker");
        setMinimumSize(new java.awt.Dimension(400, 425));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        instructionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        instructionLabel.setText("Just Starting!");
        instructionPanel.add(instructionLabel);

        getContentPane().add(instructionPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            this.bcio.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Clean Up Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instructionLabel;
    private bbct.gui.MainPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    private BaseballCardIO bcio = null;
}
