package bbct.gui;

import bbct.data.BaseballCardIO;
import bbct.exceptions.IOException;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 * TODO: JavaDoc
 *
 * @author codeguru <codeguru@users.sourceforge.net>
 */
public class BBCTFrame extends javax.swing.JFrame {

    /**
     * Name used for card with {@link MainPanel}.
     */
    public static final String MENU_CARD_NAME = "menu";
    /**
     * Name used for card with {@link AddCardsPanel}.
     */
    public static final String ADD_CARDS_CARD_NAME = "addCards";
    /**
     * Name used for card with {@link FindCardsMenuPanel}.
     */
    public static final String FIND_CARDS_MENU_CARD_NAME = "findCardsMenu";
    /**
     * Name used for card with {@link EditCardPanel}.
     */
    public static final String EDIT_CARDS_PANEL_NAME = "editCards";
    /**
     * 
     */
    public static final String FIND_CARDS_BY_YEAR_CARD_NAME = "findCardsByYear";
    /**
     * 
     */
    public static final String FIND_CARDS_BY_NUMBER_CARD_NAME = "findCardsByNumber";
    /**
     * 
     */
    public static final String FIND_CARDS_BY_YEAR_AND_NUMBER_CARD_NAME = "findCardsByYearAndNumber";
    /**
     * 
     */
    public static final String FIND_CARDS_BY_PLAYER_NAME_CARD_NAME = "findCardsByPlayerName";
    /**
     * Name used for card with {@link AboutPanel}.
     */
    public static final String ABOUT_CARD_NAME = "aboutPanel";

    /**
     * Creates new form BBCTFrame
     */
    public BBCTFrame() {
        this.initComponents();
        this.centerFrame();
    }

    /**
     * Creates new form BBCTFrame
     *
     * @param bcio
     */
    public BBCTFrame(BaseballCardIO bcio) {
        this.bcio = bcio;
        this.initComponents();
        this.centerFrame();
    }

    /**
     *
     * @param instructions
     */
    public void setInstructions(String instructions) {
        this.instructionPanel.setInstructions(instructions);
    }

    /**
     * 
     * @param cmpnt
     * @param cardName
     */
    public void addToMainPanel(Component cmpnt, String cardName) {
        this.mainPanel.add(cmpnt, cardName);
    }

    private void centerFrame() {
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - this.getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - this.getHeight()) / 2);

        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new MainPanel(this.bcio);
        instructionPanel = new bbct.gui.InstructionPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Baseball Card Tracker");
        setMinimumSize(new java.awt.Dimension(400, 425));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
        getContentPane().add(instructionPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            this.bcio.close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Clean Up Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private bbct.gui.InstructionPanel instructionPanel;
    private bbct.gui.MainPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    private BaseballCardIO bcio = null;
}
