package bbct.gui;

/**
 *
 * TODO: JavaDoc
 *
 * @author codeguru <codeguru@users.sourceforge.net>
 */
public class InstructionPanel extends javax.swing.JPanel {

    /**
     * Creates new form InstructionPanel
     */
    public InstructionPanel() {
        initComponents();
    }

    /**
     * 
     * @param instructions
     */
    public void setInstructions(String instructions) {
        this.instructionLabel.setText(instructions);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        instructionLabel = new javax.swing.JLabel();

        instructionLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        instructionLabel.setText("Test");
        add(instructionLabel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instructionLabel;
    // End of variables declaration//GEN-END:variables
}
