/*
 * This file is part of BBCT.
 *
 * Copyright 2012 codeguru <codeguru@users.sourceforge.net>
 *
 * BBCT is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * BBCT is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package bbct.gui;

import bbct.data.BaseballCardIO;

/**
 *
 * {@link MainPanel} contains all the other {@link javax.swing.JPanel}s used in
 * the BBCT application. A {@link java.awt.CardLayout} selects which
 * {@link javax.swing.JPanel} is displayed.
 * 
 * @see MenuPanel
 * @see AddCardsPanel
 * @see FindCardsPanel
 * @see FindCardsByPanel
 * @see FindCardsByYearPanel
 * @see FindCardsByNumberPanel
 * @see FindCardsByYearAndNumberPanel
 * @see FindCardsByPlayerNamePanel
 * @see AboutPanel
 *
 * @author codeguru <codeguru@users.sourceforge.net>
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates a new {@link MainPanel}.
     */
    public MainPanel() {
        initComponents();
    }

    /**
     * Creates a new {@link MainPanel}.
     *
     * @param bcio
     */
    public MainPanel(BaseballCardIO bcio) {
        this.bcio = bcio;

        initComponents();

        FindCardsByPanel yearInputPanel = new FindCardsByYearPanel(this.bcio);
        FindCardsPanel findCardsByYearPanel = new FindCardsPanel(bcio, yearInputPanel);
        this.add(findCardsByYearPanel, BBCTFrame.FIND_CARDS_BY_YEAR_CARD_NAME);

        FindCardsByPanel numberInputPanel = new FindCardsByNumberPanel(this.bcio);
        FindCardsPanel findCardsByNumberPanel = new FindCardsPanel(bcio, numberInputPanel);
        this.add(findCardsByNumberPanel, BBCTFrame.FIND_CARDS_BY_NUMBER_CARD_NAME);

        FindCardsByPanel yearAndNumberInputPanel = new FindCardsByYearAndNumberPanel(this.bcio);
        FindCardsPanel findCardsByYearAndNumberPanel = new FindCardsPanel(bcio, yearAndNumberInputPanel);
        this.add(findCardsByYearAndNumberPanel, BBCTFrame.FIND_CARDS_BY_YEAR_AND_NUMBER_CARD_NAME);

        FindCardsByPanel playerNameInputPanel = new FindCardsByPlayerNamePanel(this.bcio);
        FindCardsPanel findCardsByPlayerNamePanel = new FindCardsPanel(bcio, playerNameInputPanel);
        this.add(findCardsByPlayerNamePanel, BBCTFrame.FIND_CARDS_BY_PLAYER_NAME_CARD_NAME);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bbct.gui.MenuPanel menuPanel = new bbct.gui.MenuPanel();
        bbct.gui.AddCardsPanel addCardsPanel = new AddCardsPanel(this.bcio);
        bbct.gui.FindCardsMenuPanel findCardsMenuPanel = new FindCardsMenuPanel(this.bcio);
        bbct.gui.AboutPanel aboutPanel = new bbct.gui.AboutPanel();

        setLayout(new java.awt.CardLayout());
        add(menuPanel, "menu");
        add(addCardsPanel, "addCards");
        add(findCardsMenuPanel, "findCardsMenu");
        add(aboutPanel, "about");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private BaseballCardIO bcio = null;
}
