package bbct.gui;

import bbct.data.BaseballCardIO;
import java.awt.Container;

/**
 *
 * TODO: JavaDoc
 *
 * @author codeguru <codeguru@users.sourceforge.net>
 */
public class MainPanel extends javax.swing.JPanel {

    /**
     * Creates {@link MainPanel}.
     */
    public MainPanel() {
        initComponents();
    }
    
    /**
     * Creates {@link MainPanel}.
     * @param bcio 
     */
    public MainPanel(BaseballCardIO bcio) {
        this.bcio = bcio;
        
        initComponents();
        
        FindCardsByPanel yearInputPanel = new FindCardsByYearPanel(this.bcio);
        FindCardsPanel findCardsByYearPanel = new FindCardsPanel(bcio, yearInputPanel);
        this.add(findCardsByYearPanel, BBCTFrame.FIND_CARDS_BY_YEAR_CARD_NAME);

        FindCardsByPanel numberInputPanel = new FindCardsByNumberPanel(this.bcio);
        FindCardsPanel findCardsByNumberPanel = new FindCardsPanel(bcio, numberInputPanel);
        this.add(findCardsByNumberPanel, BBCTFrame.FIND_CARDS_BY_NUMBER_CARD_NAME);

        FindCardsByPanel yearAndNumberInputPanel = new FindCardsByYearAndNumberPanel(this.bcio);
        FindCardsPanel findCardsByYearAndNumberPanel = new FindCardsPanel(bcio, yearAndNumberInputPanel);
        this.add(findCardsByYearAndNumberPanel, BBCTFrame.FIND_CARDS_BY_YEAR_AND_NUMBER_CARD_NAME);

        FindCardsByPanel playerNameInputPanel = new FindCardsByPlayerNamePanel(this.bcio);
        FindCardsPanel findCardsByPlayerNamePanel = new FindCardsPanel(bcio, playerNameInputPanel);
        this.add(findCardsByPlayerNamePanel, BBCTFrame.FIND_CARDS_BY_PLAYER_NAME_CARD_NAME);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bbct.gui.MenuPanel menuPanel = new bbct.gui.MenuPanel();
        bbct.gui.AddCardsPanel addCardsPanel = new AddCardsPanel(this.bcio);
        bbct.gui.FindCardsMenuPanel findCardsMenuPanel = new FindCardsMenuPanel(this.bcio);
        bbct.gui.AboutPanel aboutPanel = new bbct.gui.AboutPanel();

        setLayout(new java.awt.CardLayout());
        add(menuPanel, "menu");
        add(addCardsPanel, "addCards");
        add(findCardsMenuPanel, "findCardsMenu");
        add(aboutPanel, "about");
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private BaseballCardIO bcio = null;
}
