package bbct.gui;

import java.awt.CardLayout;
import java.awt.Container;

/**
 * TODO: JavaDoc
 *
 * @author codeguru <codeguru@users.sourceforge.net>
 */
public class MenuPanel extends javax.swing.JPanel {

    /**
     * Creates new form MainPanel
     */
    public MenuPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton addCardsButton = new javax.swing.JButton();
        javax.swing.JButton findCardsButton = new javax.swing.JButton();
        javax.swing.JButton aboutButton = new javax.swing.JButton();
        javax.swing.JButton exitButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(75, 110, 75, 110));
        setMinimumSize(new java.awt.Dimension(370, 370));
        setName("mainPanel");
        setPreferredSize(new java.awt.Dimension(370, 370));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridLayout(4, 1, 0, 30));

        addCardsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        addCardsButton.setText("Add Cards");
        addCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCardsButtonActionPerformed(evt);
            }
        });
        add(addCardsButton);

        findCardsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        findCardsButton.setText("Find Cards");
        findCardsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findCardsButtonActionPerformed(evt);
            }
        });
        add(findCardsButton);

        aboutButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        aboutButton.setText("About");
        aboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutButtonActionPerformed(evt);
            }
        });
        add(aboutButton);

        exitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        add(exitButton);
    }// </editor-fold>//GEN-END:initComponents

    private void addCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCardsButtonActionPerformed
        Container parent = this.getParent();
        CardLayout cl = (CardLayout) parent.getLayout();

        cl.show(parent, BBCTFrame.ADD_CARDS_CARD_NAME);
    }//GEN-LAST:event_addCardsButtonActionPerformed

    private void findCardsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findCardsButtonActionPerformed
        Container parent = this.getParent();
        CardLayout cl = (CardLayout) parent.getLayout();

        cl.show(parent, BBCTFrame.FIND_CARDS_CARD_NAME);
    }//GEN-LAST:event_findCardsButtonActionPerformed

    private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
        Container parent = this.getParent();
        CardLayout cl = (CardLayout) parent.getLayout();

        cl.show(parent, BBCTFrame.ABOUT_CARD_NAME);
    }//GEN-LAST:event_aboutButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        BBCTFrame frame = (BBCTFrame) this.getParent().getParent().getParent().getParent().getParent();

        frame.setTitle(GUIResources.MAIN_PANEL_TITLE);
        frame.setInstructions("Chose an option:");
    }//GEN-LAST:event_formComponentShown

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
