# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: "beta",
      package_name: "bbct.android",
      apk: "android/lite/release/android-lite-release.aab"
    )
    upload_to_play_store(
      track: "beta",
      package_name: "bbct.android.premium",
      apk: "android/premium/release/android-premium-release.aab"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: "beta",
      package_name: "bbct.android",
      apk: "android/lite/release/android-lite-release.aab"
    )
    upload_to_play_store(
      track: "beta",
      package_name: "bbct.android.premium",
      apk: "android/premium/release/android-premium-release.aab"
    )
  end
end
